import { useState, useEffect, useRef } from 'react';

const H = "#F59E0B", B = "#3B82F6", gA = "#2D8B4E", gB = "#258043";

const STEPS = [
  { n: "Start match", l: "Getting started", d: "A white ball pulses at the centre circle. Tap it to pick which team takes the first centre pass. The ball and halo change to that team\u2019s colour.", t: "Amber arrows point down (home attacks down). Blue arrows point up (away attacks up).", a: "start" },
  { n: "Passing", l: "Moving the ball", d: "Tap any zone to move the ball there. It snaps to the centre of that zone. A ghost ball and dashed trail show where the ball came from.", t: "Tap the zone where you want the ball to go. Follow the actual play.", a: "pass" },
  { n: "Turnover", l: "Switching possession", d: "Tap the ball itself (not a zone) to switch possession. The halo flips colour. OUT strip arrows also flip direction and colour instantly.", t: "Watch the arrows change when possession swaps.", a: "turnover" },
  { n: "Overhead", l: "Aerial play", d: "Press and hold the ball, then drag to the target zone. A blue dashed line appears and the \u2018\u2191 Overhead\u2019 label shows at the receiving end.", t: "The blue indicator during drag is a visual guide \u2014 possession doesn\u2019t change.", a: "overhead" },
  { n: "Out", l: "Sideline", d: "Tap the OUT strip next to the zone where the ball went out. It highlights in the team\u2019s colour. Possession switches, arrows flip, and the ball repositions.", t: "Tap the same OUT strip again to reverse the call.", a: "out" },
  { n: "Dead ball", l: "Backline \u2014 dead", d: "Tap DEAD (flashing) when the ball crosses the backline off the attacking team. The defending team restarts from their quarter.", t: "The ball repositions near the backline in the defender\u2019s quarter.", a: "dead" },
  { n: "Long corner", l: "Backline \u2014 LC", d: "Tap LC (flashing) when the ball crosses the backline off the defending team. The attacking team gets a long corner \u2014 ball stays on the same side.", t: "Possession goes to the attacking team. The ball restarts on the side where LC was tapped.", a: "lc" },
  { n: "D-entries", l: "Circle entry", d: "Ball starts in front of the D. Tap the D arc \u2014 ball moves inside and the 8-option popup appears: Goal, Short Corner, Shot on Goal, Shot off Target, Penalty, Long Corner, Lost Possession, Dead Ball.", t: "The popup stays open after shots \u2014 record multiple attempts from the same D entry.", a: "dentry" },
  { n: "Short corners", l: "Set pieces", d: "From the D popup, tap Short Corner. Ball moves to the SC start position on the backline. Push outside D, then back in \u2014 full popup reappears for the outcome.", t: "Short corners are tracked separately from open play for coach analytics.", a: "sc" },
  { n: "Actions", l: "Cards & penalties", d: "The \u26A1 button flashes on the backline. Tap it to see: Green Card, Yellow Card, Short Corner, Penalty. These don\u2019t move the ball.", t: "Cards are important for match narrative and context.", a: "actions" },
  { n: "Pause & resume", l: "Match flow", d: "Tap \u23F8 Pause (flashing below). Overlay appears, timer stops. Button changes to \u25B6 Resume \u2014 tap to continue.", t: "Always pause at breaks for accurate possession and territory stats.", a: "pause" },
  { n: "Undo", l: "Fix mistakes", d: "Tap \u21A9 Undo (flashing below) to remove the last event. Ball returns to its previous position.", t: "Undo is always one tap away.", a: "undo" },
  { n: "Field rotation", l: "Swap ends", d: "Tap \uD83D\uDD04 (flashing above field) to flip. Teams typically swap ends at half breaks.", t: "Flip so the field matches what you see from the stands.", a: "rotate" },
  { n: "End match", l: "Finishing up", d: "Tap \u23F9 End (flashing below). Events saved, stats computed, coach analytics available.", t: "Always end properly \u2014 triggers stat computation and credits.", a: "end" },
];

export default function TrainingWizard({ onComplete, completedSteps = [], onStepView }) {
  const [cur, setCur] = useState(0);
  const cRef = useRef(null);
  const tRef = useRef(null);

  useEffect(() => { return () => { if (tRef.current) clearInterval(tRef.current); }; }, []);
  useEffect(() => { if (tRef.current) clearInterval(tRef.current); tRef.current = null; setTimeout(() => { if (cRef.current) runStep(); }, 50); if (onStepView) onStepView(cur); }, [cur]);

  const $ = (id) => cRef.current?.querySelector('#' + id);

  function runStep() {
    const fld = $('fld'), ctl = $('ctl'), pb2 = $('pb2');
    if (!fld || !ctl || !pb2) return;
    const s = STEPS[cur]; let pc = H;

    const bl = (c) => `<div style="position:relative;display:inline-flex;align-items:center;justify-content:center;z-index:10"><div style="position:absolute;width:50px;height:50px;border-radius:50%;background:${c}55;box-shadow:0 0 20px ${c}99,0 0 40px ${c}66;animation:tw-hp 1.8s ease-in-out infinite"></div><div style="width:22px;height:22px;border-radius:50%;background:#F8FAFC;border:3px solid ${c};box-shadow:0 0 8px ${c}88;z-index:2"></div></div>`;
    const gh = () => '<div style="width:16px;height:16px;border-radius:50%;background:#94A3B8;border:2px solid #64748B;opacity:0.4"></div>';
    const sb = () => '<div style="width:30px;height:30px;border-radius:50%;background:#F8FAFC;border:3px solid #94A3B8;animation:tw-pb 2s infinite"></div>';
    const arSvg = (c, up) => `<svg width="14" height="20" viewBox="0 0 14 20" style="position:absolute;left:50%;transform:translateX(-50%);${up ? 'top:4px' : 'bottom:4px'};pointer-events:none;opacity:0.8"><polygon points="${up ? '7,2 13,16 1,16' : '7,18 13,4 1,4'}" fill="${c}"/></svg>`;

    const setA = (c, up) => { for (let r = 0; r < 4; r++) ['ol', 'or'].forEach(s => { const o = $(`${s}${r}`); if (!o) return; const sv = o.querySelector('svg'); if (sv) sv.remove(); o.insertAdjacentHTML('beforeend', arSvg(c, up)); }); };
    const pt = (pid, h, id, ex) => { const p = $(pid); if (!p) return; const d = document.createElement('div'); if (id) d.id = id; d.style.cssText = 'position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:10;' + (ex || ''); d.innerHTML = h; p.appendChild(d); };
    const rm = (id) => { const e = $(id); if (e) e.remove(); };
    const ov = (h) => { const o = $('ov'); if (o) o.innerHTML = h; };
    const fl = (id) => { const e = $(id); if (e) e.style.animation = 'tw-bk 0.6s infinite'; };
    const uf = (id) => { const e = $(id); if (e) e.style.animation = ''; };

    const sp = (c, n) => { pc = c; pb2.innerHTML = `<div style="font-size:9px;font-weight:700;padding:2px 10px;border-radius:99px;display:inline-flex;align-items:center;gap:4px;color:${c};background:${c}22"><div style="width:6px;height:6px;border-radius:50%;background:${c}"></div>${n}</div><div id="fbtn" style="padding:3px 8px;border-radius:6px;border:1px solid #334155;background:#1E293B;color:#94A3B8;font-size:10px;font-weight:700">\uD83D\uDD04</div>`; setA(c, c === B); };
    const sctl = (items) => { ctl.innerHTML = items.map(i => `<div id="${i[2]}" style="padding:6px 14px;border-radius:8px;border:none;font-size:12px;font-weight:700;background:${i[0]};color:${i[1]};transition:all 0.3s">${i[3]}</div>`).join(''); };

    const mkBl = (t, p) => `<div style="display:flex;height:28px;background:#1a3a2a" id="bl-${p}"><div id="dd-${p}-l" style="width:50px;display:flex;align-items:center;justify-content:center;font-size:7px;font-weight:700;color:#94A3B8;text-transform:uppercase;background:#162D22;transition:background 0.3s">Dead</div><div id="lc-${p}-l" style="width:46px;display:flex;align-items:center;justify-content:center;font-size:7px;font-weight:700;color:#F59E0B;text-transform:uppercase;background:#1E3A2F;transition:background 0.3s">\u25C1 LC</div><div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;position:relative"><span style="font-size:9px;font-weight:800;color:${t.c};text-transform:uppercase;letter-spacing:0.1em;line-height:1">${t.s}</span><span style="font-size:6px;font-weight:600;color:#64748B;text-transform:uppercase;line-height:1;margin-top:1px">${t.n}</span><div id="act-${p}" style="position:absolute;right:4px;top:50%;transform:translateY(-50%);width:20px;height:20px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:800;z-index:18;border:1.5px solid ${t.c}66;color:${t.c};transition:all 0.3s">\u26A1</div></div><div id="lc-${p}-r" style="width:46px;display:flex;align-items:center;justify-content:center;font-size:7px;font-weight:700;color:#F59E0B;text-transform:uppercase;background:#1E3A2F;transition:background 0.3s">LC \u25B7</div><div id="dd-${p}-r" style="width:50px;display:flex;align-items:center;justify-content:center;font-size:7px;font-weight:700;color:#94A3B8;text-transform:uppercase;background:#162D22;transition:background 0.3s">Dead</div></div>`;

    const buildF = (flip) => {
      const hm = { n: 'Demo Lions', s: 'DLI', c: H }, aw = { n: 'Demo Eagles', s: 'DEA', c: B };
      const tn = flip ? [aw, hm] : [hm, aw];
      let h = mkBl(tn[0], 'top');
      for (let r = 0; r < 4; r++) {
        if (r === 2) h += '<div style="height:1px;background:rgba(255,255,255,0.15);position:relative"><div style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:22px;height:22px;border-radius:50%;border:1.5px solid rgba(255,255,255,0.18)"></div><div id="cb" style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:15;display:none"></div></div>';
        h += '<div style="display:flex;height:68px">';
        h += `<div id="ol${r}" style="width:26px;display:flex;align-items:center;justify-content:center;background:#334155;position:relative;opacity:0.6;transition:all 0.3s"><span style="font-size:7px;font-weight:800;color:#CBD5E1;writing-mode:vertical-rl;letter-spacing:0.05em">OUT</span></div>`;
        for (let c = 0; c < 3; c++) h += `<div id="z${r}${c}" style="flex:1;position:relative;display:flex;align-items:center;justify-content:center;background:${r % 2 === 0 ? gA : gB};border-right:${c < 2 ? '1px solid rgba(255,255,255,0.06)' : 'none'}"></div>`;
        h += `<div id="or${r}" style="width:26px;display:flex;align-items:center;justify-content:center;background:#334155;position:relative;opacity:0.6;transition:all 0.3s"><span style="font-size:7px;font-weight:800;color:#CBD5E1;writing-mode:vertical-rl;letter-spacing:0.05em">OUT</span></div></div>`;
      }
      h += mkBl(tn[1], 'bot');
      h += `<div style="position:absolute;left:50%;transform:translateX(-50%);top:28px;width:80px;height:22px;z-index:15"><div style="width:80px;height:22px;border-bottom-left-radius:40px;border-bottom-right-radius:40px;border:3px solid ${tn[0].c};border-top:none;background:${tn[0].c}55"></div></div>`;
      h += `<div id="dab" style="position:absolute;left:50%;transform:translateX(-50%);bottom:28px;width:80px;height:22px;z-index:15"><div id="dabs" style="width:80px;height:22px;border-top-left-radius:40px;border-top-right-radius:40px;border:3px solid ${tn[1].c};border-bottom:none;background:${tn[1].c}55"></div></div>`;
      h += '<div id="ov" style="position:absolute;inset:0;z-index:16;pointer-events:none"></div>';
      fld.innerHTML = h; setA(pc, pc === B);
    };

    const dpop = `<div style="position:absolute;z-index:22;background:#0F172Aee;border:1px solid #33415566;border-radius:12px;padding:8px;display:flex;flex-direction:column;gap:4px;min-width:170px;left:50%;transform:translateX(-50%);bottom:58px">${[['Goal!',H,1],['Short Corner','#8B5CF6',0],['Shot on Goal','#10B981',0],['Shot off Target','#6B7280',0],['Penalty',H,0],['Long Corner',B,0],['Lost Possession','#EF4444',0],['Dead Ball','#94A3B8',0]].map(x=>`<div style="padding:6px 10px;border-radius:6px;font-size:11px;font-weight:700;color:#F8FAFC;display:flex;align-items:center;gap:8px;border:1px solid ${x[1]}44;background:${x[1]}18${x[2]?';border-color:'+x[1]+'88':''}">${x[0]}</div>`).join('')}</div>`;

    buildF(false); sp(H, 'DLI');
    sctl([[H,'#0B0F1A','cpa','\u23F8 Pause'],['#EF4444','#FFF','cend','\u23F9 End'],['#1E293B','#94A3B8','cun','\u21A9 Undo']]);
    pb2.style.display = 'flex';
    const a = s.a;

    if(a==='start'){pb2.style.display='none';ctl.innerHTML='';const cb=$('cb');if(cb){cb.style.display='block';cb.innerHTML=`<div style="display:flex;flex-direction:column;align-items:center;gap:6px">${sb()}<div style="font-size:8px;font-weight:700;color:#F8FAFC;text-transform:uppercase;letter-spacing:0.08em;white-space:nowrap;background:rgba(15,23,42,0.85);padding:3px 10px;border-radius:6px">Tap ball to start</div></div>`;}let fr=0;tRef.current=setInterval(()=>{fr=(fr+1)%4;const cb=$('cb');if(!cb)return;if(fr===0||fr===2){cb.innerHTML=`<div style="display:flex;flex-direction:column;align-items:center;gap:6px">${sb()}<div style="font-size:8px;font-weight:700;color:#F8FAFC;text-transform:uppercase;letter-spacing:0.08em;white-space:nowrap;background:rgba(15,23,42,0.85);padding:3px 10px;border-radius:6px">Tap ball to start</div></div>`;setA('#94A3B8',false);}if(fr===1){cb.innerHTML=`<div style="display:flex;flex-direction:column;align-items:center;gap:4px">${bl(H)}<div style="font-size:8px;font-weight:700;color:${H};white-space:nowrap">DLI attacks \u2193</div></div>`;sp(H,'DLI');}if(fr===3){cb.innerHTML=`<div style="display:flex;flex-direction:column;align-items:center;gap:4px">${bl(B)}<div style="font-size:8px;font-weight:700;color:${B};white-space:nowrap">DEA attacks \u2191</div></div>`;sp(B,'DEA');}},1500);}

    if(a==='pass'){const zs=['z11','z01','z21'];let fr=0;pt(zs[0],bl(H),'bw');tRef.current=setInterval(()=>{const pv=zs[fr];fr=(fr+1)%zs.length;const nx=zs[fr];rm('bw');rm('gw');ov('');pt(pv,gh(),'gw');pt(nx,bl(H),'bw');const p1=$(pv),p2=$(nx);if(p1&&p2&&fld){const r1=p1.getBoundingClientRect(),r2=p2.getBoundingClientRect(),rf=fld.getBoundingClientRect();ov(`<svg style="width:100%;height:100%"><line x1="${r1.left+r1.width/2-rf.left}" y1="${r1.top+r1.height/2-rf.top}" x2="${r2.left+r2.width/2-rf.left}" y2="${r2.top+r2.height/2-rf.top}" stroke="#94A3B8" stroke-width="2" stroke-dasharray="6 4" opacity="0.5"/></svg>`);}},1400);}

    if(a==='turnover'){let isH=true;pt('z21',bl(H),'bw');tRef.current=setInterval(()=>{isH=!isH;rm('bw');pt('z21',bl(isH?H:B),'bw');sp(isH?H:B,isH?'DLI':'DEA');},1500);}

    if(a==='overhead'){let fr=0;pt('z30',bl(H),'bw');tRef.current=setInterval(()=>{fr=(fr+1)%4;rm('bw');ov('');if(fr===0){pt('z30',bl(H),'bw');}if(fr===1||fr===2){pt('z30',bl(H),'bw');const z1=$('z30'),z2=$('z10');if(z1&&z2&&fld){const r1=z1.getBoundingClientRect(),r2=z2.getBoundingClientRect(),rf=fld.getBoundingClientRect();const x1=r1.left+r1.width/2-rf.left,y1=r1.top+r1.height/2-rf.top,x2=r2.left+r2.width/2-rf.left,y2=r2.top+r2.height/2-rf.top;ov(`<svg style="width:100%;height:100%"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#3B82F6" stroke-width="2" stroke-dasharray="6 4" opacity="0.6"/></svg><div style="position:absolute;left:${x2}px;top:${y2}px;z-index:17;transform:translate(-50%,-50%)"><div style="width:20px;height:20px;border-radius:50%;background:#F8FAFC;border:3px solid #3B82F6;box-shadow:0 0 16px #3B82F688"></div></div><div style="position:absolute;left:${x2}px;top:${y2-20}px;transform:translateX(-50%);z-index:18;background:#3B82F6;color:#fff;padding:2px 8px;border-radius:6px;font-size:9px;font-weight:700;white-space:nowrap">\u2191 Overhead</div>`);}}if(fr===3){pt('z10',bl(H),'bw');}},1300);}

    if(a==='out'){let fr=0;pt('z21',bl(H),'bw');sp(H,'DLI');tRef.current=setInterval(()=>{fr=(fr+1)%4;rm('bw');ov('');if(fr===0){buildF(false);sp(H,'DLI');pt('z21',bl(H),'bw');fl('or2');}if(fr===1){uf('or2');const o=$('or2');if(o){o.style.background=H;o.style.opacity='1';}pt('z22',bl(H),'bw');}if(fr===2){sp(B,'DEA');const o=$('or2');if(o){o.style.background=B;o.style.opacity='1';}pt('z22',bl(B),'bw');ov(`<div style="position:absolute;right:40px;top:50%;transform:translateY(-50%);font-size:9px;font-weight:700;color:${B};white-space:nowrap;z-index:22;background:#0F172Aee;padding:2px 8px;border-radius:4px">DEA free hit</div>`);}if(fr===3){sp(B,'DEA');pt('z22',bl(B),'bw');}},1500);}

    if(a==='dead'){let fr=0;tRef.current=setInterval(()=>{fr=(fr+1)%3;rm('bw');ov('');buildF(false);sp(H,'DLI');if(fr===0){pt('z01',bl(H),'bw');fl('dd-top-l');ov('<div style="position:absolute;left:18px;top:6px;font-size:8px;color:#F59E0B;z-index:22;font-weight:600;animation:tw-bk 0.6s infinite">DEAD \u2193</div>');}if(fr===1){uf('dd-top-l');sp(H,'DLI');pt('z00',bl(H),'bw','top:auto;bottom:-2px');ov(`<div style="position:absolute;left:50%;top:40px;transform:translateX(-50%);font-size:9px;font-weight:700;color:${H};white-space:nowrap;z-index:22;background:#0F172Aee;padding:2px 8px;border-radius:4px">DLI restart (dead ball)</div>`);}if(fr===2){pt('z01',bl(H),'bw');}},2000);}

    if(a==='lc'){let fr=0;tRef.current=setInterval(()=>{fr=(fr+1)%3;rm('bw');ov('');buildF(false);sp(H,'DLI');if(fr===0){pt('z01',bl(H),'bw');fl('lc-top-r');ov('<div style="position:absolute;right:16px;top:6px;font-size:8px;color:#F59E0B;z-index:22;font-weight:600;animation:tw-bk 0.6s infinite">LC \u2193</div>');}if(fr===1){uf('lc-top-r');sp(H,'DLI');pt('z02',bl(H),'bw','top:-2px');ov(`<div style="position:absolute;left:50%;top:40px;transform:translateX(-50%);font-size:9px;font-weight:700;color:${H};white-space:nowrap;z-index:22;background:#0F172Aee;padding:2px 8px;border-radius:4px">DLI long corner (right side)</div>`);}if(fr===2){pt('z01',bl(H),'bw');}},2000);}

    if(a==='dentry'){let fr=0;tRef.current=setInterval(()=>{fr=(fr+1)%4;rm('bw');rm('dbw');ov('');const dabs=$('dabs');if(fr===0){pt('z31',bl(H),'bw','top:auto;bottom:4px');if(dabs)dabs.style.background=B+'55';}if(fr===1){if(dabs)dabs.style.background=B+'88';const da=$('dab');if(da){const d=document.createElement('div');d.id='dbw';d.style.cssText='position:absolute;left:50%;bottom:2px;transform:translateX(-50%);z-index:16';d.innerHTML=bl(H);da.appendChild(d);}}if(fr===2){if(dabs)dabs.style.background=B+'88';const da=$('dab');if(da){const d=document.createElement('div');d.id='dbw';d.style.cssText='position:absolute;left:50%;bottom:2px;transform:translateX(-50%);z-index:16';d.innerHTML=bl(H);da.appendChild(d);}ov(dpop);}if(fr===3){if(dabs)dabs.style.background=B+'88';const da=$('dab');if(da){const d=document.createElement('div');d.id='dbw';d.style.cssText='position:absolute;left:50%;bottom:2px;transform:translateX(-50%);z-index:16';d.innerHTML=bl(H);da.appendChild(d);}}},1600);}

    if(a==='sc'){let fr=0;tRef.current=setInterval(()=>{fr=(fr+1)%5;rm('bw');rm('dbw');ov('');const dabs=$('dabs');if(dabs)dabs.style.background=B+'55';if(fr===0){const blbot=$('bl-bot');if(blbot){const m=blbot.children[2];if(m){const d=document.createElement('div');d.id='bw';d.style.cssText='position:absolute;left:calc(50% + 50px);top:-10px;z-index:16';d.innerHTML=bl(H);m.appendChild(d);}}ov('<div style="position:absolute;bottom:34px;left:50%;transform:translateX(-50%);font-size:9px;font-weight:700;color:#8B5CF6;white-space:nowrap;background:#8B5CF622;padding:2px 8px;border-radius:4px;z-index:22">SC start position</div>');}if(fr===1){pt('z31',bl(H),'bw');ov('<div style="position:absolute;bottom:80px;left:50%;transform:translateX(-50%);font-size:9px;color:#94A3B8;z-index:22;background:#0F172Aee;padding:2px 6px;border-radius:4px">Push outside D...</div>');}if(fr===2){if(dabs)dabs.style.background=B+'88';const da=$('dab');if(da){const d=document.createElement('div');d.id='dbw';d.style.cssText='position:absolute;left:50%;bottom:2px;transform:translateX(-50%);z-index:16';d.innerHTML=bl(H);da.appendChild(d);}ov(dpop);}if(fr===3){if(dabs)dabs.style.background=B+'88';const da=$('dab');if(da){const d=document.createElement('div');d.id='dbw';d.style.cssText='position:absolute;left:50%;bottom:2px;transform:translateX(-50%);z-index:16';d.innerHTML=bl(H);da.appendChild(d);}}if(fr===4){pt('z31',bl(H),'bw');}},1800);}

    if(a==='actions'){let fr=0;pt('z21',bl(H),'bw');tRef.current=setInterval(()=>{fr=(fr+1)%3;ov('');if(fr===0){fl('act-bot');}if(fr===1){uf('act-bot');ov(`<div style="position:absolute;z-index:22;background:#0F172Aee;border:1px solid #33415566;border-radius:12px;padding:8px;display:flex;flex-direction:column;gap:4px;min-width:170px;left:50%;transform:translateX(-50%);bottom:34px">${[['Green Card','#22C55E','\uD83D\uDFE2'],['Yellow Card','#F59E0B','\uD83D\uDFE1'],['Short Corner','#8B5CF6','\uD83D\uDD32'],['Penalty','#EF4444','\u26A0\uFE0F']].map(x=>`<div style="padding:6px 10px;border-radius:6px;font-size:11px;font-weight:700;color:#F8FAFC;display:flex;align-items:center;gap:8px;border:1px solid ${x[1]}44;background:${x[1]}18"><span style="font-size:14px">${x[2]}</span>${x[0]}</div>`).join('')}</div>`);}if(fr===2){ov('');}},1600);}

    if(a==='pause'){let fr=0;pt('z11',bl(H),'bw');tRef.current=setInterval(()=>{fr=(fr+1)%4;ov('');if(fr===0){fl('cpa');}if(fr===1){uf('cpa');ov('<div style="position:absolute;inset:0;z-index:25;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,0.35)"><div style="font-size:14px;font-weight:800;color:#F59E0B;text-transform:uppercase;letter-spacing:0.1em;background:rgba(15,23,42,0.85);padding:6px 20px;border-radius:10px;border:1px solid #F59E0B44">\u23F8 Paused</div></div>');sctl([['#10B981','#FFF','cres','\u25B6 Resume'],['#EF4444','#FFF','cend','\u23F9 End'],['#1E293B','#94A3B8','cun','\u21A9 Undo']]);}if(fr===2){fl('cres');}if(fr===3){uf('cres');ov('');sctl([[H,'#0B0F1A','cpa','\u23F8 Pause'],['#EF4444','#FFF','cend','\u23F9 End'],['#1E293B','#94A3B8','cun','\u21A9 Undo']]);}},1800);}

    if(a==='undo'){let fr=0;pt('z21',bl(H),'bw');tRef.current=setInterval(()=>{fr=(fr+1)%4;rm('bw');ov('');if(fr===0){pt('z21',bl(H),'bw');}if(fr===1){pt('z01',bl(H),'bw');fl('cun');}if(fr===2){uf('cun');pt('z21',bl(H),'bw');ov('<div style="position:absolute;top:8px;right:8px;z-index:22;background:#10B98122;border:1px solid #10B98144;border-radius:8px;padding:4px 12px;font-size:11px;font-weight:700;color:#10B981">Undone \u2713</div>');}if(fr===3){pt('z21',bl(H),'bw');}},1400);}

    if(a==='rotate'){let fr=0,flip=false;pt('z11',bl(H),'bw');tRef.current=setInterval(()=>{fr=(fr+1)%3;rm('bw');ov('');if(fr===0){pt('z11',bl(H),'bw');fl('fbtn');}if(fr===1){uf('fbtn');ov('<div style="position:absolute;inset:0;z-index:25;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,0.35)"><div style="background:rgba(15,23,42,0.9);padding:8px 20px;border-radius:10px;border:1px solid #334155;font-size:13px;font-weight:700;color:#F8FAFC">\u21C5 Rotating field...</div></div>');}if(fr===2){flip=!flip;buildF(flip);sp(H,'DLI');pt('z21',bl(H),'bw');ov('<div style="position:absolute;top:8px;left:50%;transform:translateX(-50%);z-index:22;background:#10B98122;border:1px solid #10B98144;border-radius:8px;padding:4px 12px;font-size:11px;font-weight:700;color:#10B981">Field rotated \u2713</div>');}},1600);}

    if(a==='end'){let fr=0;pt('z21',bl(H),'bw');tRef.current=setInterval(()=>{fr=(fr+1)%3;ov('');if(fr===0){fl('cend');}if(fr===1){uf('cend');ov('<div style="position:absolute;inset:0;z-index:25;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,0.35)"><div style="display:flex;flex-direction:column;align-items:center;gap:8px"><div style="font-size:14px;font-weight:800;color:#EF4444;text-transform:uppercase;letter-spacing:0.1em;background:rgba(15,23,42,0.9);padding:8px 24px;border-radius:10px;border:1px solid #EF444444">\uD83C\uDFC1 End Match</div><div style="font-size:9px;color:#94A3B8">Saving & computing stats...</div></div></div>');}if(fr===2){ov('<div style="position:absolute;inset:0;z-index:25;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,0.35)"><div style="display:flex;flex-direction:column;align-items:center;gap:8px"><div style="font-size:14px;font-weight:800;color:#10B981;background:rgba(15,23,42,0.9);padding:8px 24px;border-radius:10px;border:1px solid #10B98144">\u2713 Match saved!</div><div style="font-size:9px;color:#94A3B8">DLI 2 \u2014 1 DEA</div></div></div>');}},2000);}
  }

  const s = STEPS[cur];
  const allViewed = completedSteps.length >= STEPS.length;
  const prev = () => { if (cur > 0) setCur(cur - 1); };
  const next = () => { if (cur < STEPS.length - 1) setCur(cur + 1); else if (onComplete) onComplete(); };

  return (
    <div ref={cRef}>
      <style>{`@keyframes tw-hp{0%,100%{opacity:0.6;transform:scale(1)}50%{opacity:1;transform:scale(1.15)}}@keyframes tw-bk{0%,100%{opacity:1}50%{opacity:0.15}}@keyframes tw-pb{0%,100%{box-shadow:0 0 16px rgba(255,255,255,0.6),0 0 32px rgba(255,255,255,0.3);transform:scale(1)}50%{box-shadow:0 0 24px rgba(255,255,255,0.8),0 0 48px rgba(255,255,255,0.4);transform:scale(1.1)}}`}</style>
      <div style={{display:'flex',gap:3,justifyContent:'center',marginBottom:10,flexWrap:'wrap'}}>{STEPS.map((_,i)=>(<div key={i} onClick={()=>setCur(i)} style={{width:i===cur?14:6,height:6,borderRadius:3,cursor:'pointer',background:i===cur?'#F59E0B':completedSteps.includes(i)?'#10B981':'#334155',transition:'all 0.2s'}}/>))}</div>
      <div style={{fontSize:12,color:'#94A3B8',marginBottom:4,display:'flex',alignItems:'center',gap:8}}><div style={{width:20,height:20,borderRadius:10,background:'#F59E0B',color:'#0B0F1A',fontSize:11,fontWeight:500,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>{cur+1}</div>Step {cur+1} of {STEPS.length} — {s.l}</div>
      <div style={{fontSize:16,fontWeight:500,color:'#F8FAFC',marginBottom:4}}>{s.n}</div>
      <div style={{fontSize:13,color:'#F8FAFC',lineHeight:1.6,marginBottom:10}}>{s.d}</div>
      <div id="pb2" style={{display:'flex',justifyContent:'center',alignItems:'center',gap:8,padding:'0 14px 4px'}}/>
      <div id="fld" style={{borderRadius:10,overflow:'hidden',border:'2px solid #1a5c32',position:'relative',userSelect:'none'}}/>
      <div id="ctl" style={{display:'flex',gap:6,justifyContent:'center',padding:'6px 14px 4px',flexWrap:'wrap',marginBottom:10}}/>
      {s.t&&<div style={{fontSize:13,color:'#F59E0B',background:'#F59E0B15',padding:'8px 12px',borderRadius:8,marginBottom:14}}>{s.t}</div>}
      <div style={{display:'flex',gap:8}}>
        <button onClick={prev} disabled={cur===0} style={{flex:1,padding:10,borderRadius:8,border:'1px solid #334155',background:cur===0?'#1E293B44':'#1E293B',color:cur===0?'#33415566':'#CBD5E1',fontSize:12,fontWeight:600,cursor:cur===0?'not-allowed':'pointer'}}>Previous</button>
        <button onClick={next} style={{flex:1,padding:10,borderRadius:8,border:'none',background:cur===STEPS.length-1?'#10B981':'#F59E0B',color:'#0B0F1A',fontSize:12,fontWeight:700,cursor:'pointer'}}>{cur===STEPS.length-1?(allViewed?'Complete \u2713':'Done'):'Next'}</button>
      </div>
    </div>
  );
}

export { STEPS };
