export const theme = {
  bg: "#0F172A",
  surface: "#1E293B",
  border: "#334155",
  text: "#F8FAFC",
  textMuted: "#94A3B8",
  textDim: "#64748B",
  textDimmer: "#475569",
  accent: "#F59E0B",
  danger: "#EF4444",
  success: "#10B981",
  info: "#3B82F6",
};

export const S = {
  app: {
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
    maxWidth: 430,
    margin: "0 auto",
    background: theme.bg,
    minHeight: "100vh",
    minHeight: "100dvh",
    color: theme.text,
  },
  page: { padding: "16px" },
  nav: {
    background: theme.surface,
    padding: "14px 16px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    borderBottom: `1px solid ${theme.border}`,
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: theme.textMuted,
    fontSize: 20,
    cursor: "pointer",
    padding: "0 4px",
  },
  navTitle: {
    fontSize: 16,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  card: {
    background: theme.surface,
    borderRadius: 12,
    padding: "16px",
    marginBottom: 10,
    cursor: "pointer",
    border: `1px solid ${theme.border}`,
  },
  btn: (bg, fg) => ({
    padding: "12px 20px",
    borderRadius: 10,
    border: "none",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    background: bg,
    color: fg,
    width: "100%",
    textAlign: "center",
  }),
  btnSm: (bg, fg) => ({
    padding: "6px 14px",
    borderRadius: 8,
    border: "none",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    background: bg,
    color: fg,
  }),
  input: {
    width: "100%",
    padding: "12px",
    borderRadius: 8,
    border: `1px solid ${theme.border}`,
    background: theme.bg,
    color: theme.text,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  label: {
    fontSize: 11,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    color: theme.textDim,
    marginBottom: 6,
    display: "block",
  },
  empty: {
    textAlign: "center",
    color: theme.textDimmer,
    padding: "40px 20px",
    fontSize: 13,
  },
};
